
let menu=[
  {
    name:"首页",
    alias: "home",
    path:"/home",
    status:true,
    icon:"ios-people",
  },
  {
    name:"按摩椅状态",
    alias: "site",
    path:"/site",
    status:false,
    icon:"ios-people"
  },
  {
    name:"场所分成",
    alias: "site_profit",
    path:"/site_profit",
    status:false,
    icon:"ios-people"
  },
  {
    name:"运营管理",
    path:"/operation_manage",
    icon:"ios-people",
    children:[
      {
        name:"套餐管理",
        path:"/combo_mange",
        status:false,
        icon:"ios-people"
      },
      {
        name:"场所类型管理",
        path:"/site_mold_mange",
        status:false,
        icon:"ios-people"
      },
      {
        name:"销售代表管理",
        path:"/sell_mange",
        status:false,
        icon:"ios-people"
      },
      {
        name:"销售代表管理",
        path:"/sell_mange",
        status:false,
        icon:"ios-people"
      },
      {
        name:"销售代表管理",
        path:"/sell_mange",
        status:false,
        icon:"ios-people"
      },
      {
        name:"销售代表管理",
        path:"/sell_mange",
        status:false,
        icon:"ios-people"
      },
      {
        name:"销售代表管理",
        path:"/sell_mange",
        status:false,
        icon:"ios-people"
      },
      {
        name:"场所管理",
        path:"/site_mange",
        status:false,
        icon:"ios-people"
      }]
    },
    {
      name:"运营管理",
      path:"/operation_manage",
      icon:"ios-people",
      children:[
        {
          name:"套餐管理",
          path:"/combo_mange",
          status:false,
          icon:"ios-people"
        },
        {
          name:"场所类型管理",
          path:"/site_mold_mange",
          status:false,
          icon:"ios-people"
        },
        {
          name:"销售代表管理",
          path:"/sell_mange",
          status:false,
          icon:"ios-people"
        },
        {
          name:"销售代表管理",
          path:"/sell_mange",
          status:false,
          icon:"ios-people"
        },
        {
          name:"销售代表管理",
          path:"/sell_mange",
          status:false,
          icon:"ios-people"
        },
        {
          name:"销售代表管理",
          path:"/sell_mange",
          status:false,
          icon:"ios-people"
        },
        {
          name:"销售代表管理",
          path:"/sell_mange",
          status:false,
          icon:"ios-people"
        },
        {
          name:"场所管理",
          path:"/site_mange",
          status:false,
          icon:"ios-people"
        }]
      }
  
];
export default menu




